services:
  hand-volume:
    build: .
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/pulse
    network_mode: host
